services:
  - type: static
    name: webframe-weaver-frontend
    env: static
    plan: free
    # Render automatically runs 'npm install' before buildCommand
    buildCommand: "npm install && npm run build"
    publishPath: "dist"
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://icuspbackend.onrender.com"
